version: "3.9"

x-fenix: &fenix
  build: &fenix-build
    context: ./
    dockerfile: .github/Dockerfile
    args:
      OPENMPI_REPO: open-mpi/ompi
      OPENMPI_VERS_PREFIX: tags
      OPENMPI_VERS: v5.0.0rc10
    #Caches should be manually scoped, or they'll conflict.
    x-bake:
      cache-from:
        - type=gha,scope=default
      cache-to:
        - type=gha,scope=default,mode=max

services:
  #fenix_ompi_5rc10:
  # <<: *fenix
  # image: "fenix:ompi_5rc10"
  # build: 
  #   <<: *fenix-build
  #   x-bake:
  #     cache-from:
  #       - type=gha,scope=ompi_5rc10
  #     cache-to:
  #       - type=gha,scope=ompi_5rc10,mode=max

  fenix_ompi_5:
    <<: *fenix
    image: "fenix:ompi_5"
    build:
      <<: *fenix-build
      args:
        - OPENMPI_VERS_PREFIX=heads
        - OPENMPI_VERS=v5.0.x
      x-bake:
        cache-from:
          - type=gha,scope=ompi_5
        cache-to:
          - type=gha,scope=ompi_5,mode=max
  
  fenix_ompi_main:
    <<: *fenix
    image: "fenix:ompi_main"
    build:
      <<: *fenix-build
      args:
        - OPENMPI_VERS_PREFIX=heads
        - OPENMPI_VERS=main
      x-bake:
        cache-from:
          - type=gha,scope=ompi_main
        cache-to:
          - type=gha,scope=ompi_main,mode=max
  
  fenix_icldisco_latest:
    <<: *fenix
    image: "fenix:icldisco_latest"
    build:
      <<: *fenix-build
      args:
        - OPENMPI_REPO=icldisco/ompi
        - OPENMPI_VERS_PREFIX=heads
        - OPENMPI_VERS=ulfm/latest
      x-bake:
        cache-from:
          - type=gha,scope=icldisco_latest
        cache-to:
          - type=gha,scope=icldisco_latest,mode=max
  
  #fenix_icldisco_experimental:
  #  <<: *fenix
  #  image: fenix/icldisco
  #  build:
  #    <<: *fenix-build
  #   args:
  #     - OPENMPI_REPO=icldisco/ompi
  #     - OPENMPI_VERS_PREFIX=heads
  #     - OPENMPI_VERS=ulfm/experimental
