repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.34.0
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
