# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/projects/x86-64-haswell/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /home/projects/x86-64-haswell/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/evalen/public/Fenix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/evalen/public/Fenix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/projects/x86-64-haswell/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/projects/x86-64-haswell/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evalen/public/Fenix/CMakeFiles /home/evalen/public/Fenix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/evalen/public/Fenix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fenix

# Build rule for target.
fenix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fenix
.PHONY : fenix

# fast build rule for target.
fenix/fast:
	$(MAKE) -f src/CMakeFiles/fenix.dir/build.make src/CMakeFiles/fenix.dir/build
.PHONY : fenix/fast

#=============================================================================
# Target rules for targets named mpi_send_recv

# Build rule for target.
mpi_send_recv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_send_recv
.PHONY : mpi_send_recv

# fast build rule for target.
mpi_send_recv/fast:
	$(MAKE) -f test/sendrecv/CMakeFiles/mpi_send_recv.dir/build.make test/sendrecv/CMakeFiles/mpi_send_recv.dir/build
.PHONY : mpi_send_recv/fast

#=============================================================================
# Target rules for targets named online

# Build rule for target.
online: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 online
.PHONY : online

# fast build rule for target.
online/fast:
	$(MAKE) -f test/online/CMakeFiles/online.dir/build.make test/online/CMakeFiles/online.dir/build
.PHONY : online/fast

#=============================================================================
# Target rules for targets named fenix_hello_world

# Build rule for target.
fenix_hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fenix_hello_world
.PHONY : fenix_hello_world

# fast build rule for target.
fenix_hello_world/fast:
	$(MAKE) -f examples/01_hello_world/fenix/CMakeFiles/fenix_hello_world.dir/build.make examples/01_hello_world/fenix/CMakeFiles/fenix_hello_world.dir/build
.PHONY : fenix_hello_world/fast

#=============================================================================
# Target rules for targets named mpi_hello_world

# Build rule for target.
mpi_hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_hello_world
.PHONY : mpi_hello_world

# fast build rule for target.
mpi_hello_world/fast:
	$(MAKE) -f examples/01_hello_world/mpi/CMakeFiles/mpi_hello_world.dir/build.make examples/01_hello_world/mpi/CMakeFiles/mpi_hello_world.dir/build
.PHONY : mpi_hello_world/fast

#=============================================================================
# Target rules for targets named fenix_ring

# Build rule for target.
fenix_ring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fenix_ring
.PHONY : fenix_ring

# fast build rule for target.
fenix_ring/fast:
	$(MAKE) -f examples/02_send_recv/fenix/CMakeFiles/fenix_ring.dir/build.make examples/02_send_recv/fenix/CMakeFiles/fenix_ring.dir/build
.PHONY : fenix_ring/fast

#=============================================================================
# Target rules for targets named mpi_ring

# Build rule for target.
mpi_ring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_ring
.PHONY : mpi_ring

# fast build rule for target.
mpi_ring/fast:
	$(MAKE) -f examples/02_send_recv/mpi/CMakeFiles/mpi_ring.dir/build.make examples/02_send_recv/mpi/CMakeFiles/mpi_ring.dir/build
.PHONY : mpi_ring/fast

#=============================================================================
# Target rules for targets named fenix_reduce

# Build rule for target.
fenix_reduce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fenix_reduce
.PHONY : fenix_reduce

# fast build rule for target.
fenix_reduce/fast:
	$(MAKE) -f examples/03_reduce/fenix/CMakeFiles/fenix_reduce.dir/build.make examples/03_reduce/fenix/CMakeFiles/fenix_reduce.dir/build
.PHONY : fenix_reduce/fast

#=============================================================================
# Target rules for targets named mpi_reduce

# Build rule for target.
mpi_reduce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_reduce
.PHONY : mpi_reduce

# fast build rule for target.
mpi_reduce/fast:
	$(MAKE) -f examples/03_reduce/mpi/CMakeFiles/mpi_reduce.dir/build.make examples/03_reduce/mpi/CMakeFiles/mpi_reduce.dir/build
.PHONY : mpi_reduce/fast

#=============================================================================
# Target rules for targets named fenix_stencil_1D

# Build rule for target.
fenix_stencil_1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fenix_stencil_1D
.PHONY : fenix_stencil_1D

# fast build rule for target.
fenix_stencil_1D/fast:
	$(MAKE) -f examples/04_Isend_Irecv/fenix/CMakeFiles/fenix_stencil_1D.dir/build.make examples/04_Isend_Irecv/fenix/CMakeFiles/fenix_stencil_1D.dir/build
.PHONY : fenix_stencil_1D/fast

#=============================================================================
# Target rules for targets named mpi_stencil_1D

# Build rule for target.
mpi_stencil_1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_stencil_1D
.PHONY : mpi_stencil_1D

# fast build rule for target.
mpi_stencil_1D/fast:
	$(MAKE) -f examples/04_Isend_Irecv/mpi/CMakeFiles/mpi_stencil_1D.dir/build.make examples/04_Isend_Irecv/mpi/CMakeFiles/mpi_stencil_1D.dir/build
.PHONY : mpi_stencil_1D/fast

#=============================================================================
# Target rules for targets named subset_create

# Build rule for target.
subset_create: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subset_create
.PHONY : subset_create

# fast build rule for target.
subset_create/fast:
	$(MAKE) -f examples/05_subset_create/CMakeFiles/subset_create.dir/build.make examples/05_subset_create/CMakeFiles/subset_create.dir/build
.PHONY : subset_create/fast

#=============================================================================
# Target rules for targets named subset_createv

# Build rule for target.
subset_createv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subset_createv
.PHONY : subset_createv

# fast build rule for target.
subset_createv/fast:
	$(MAKE) -f examples/06_subset_createv/CMakeFiles/subset_createv.dir/build.make examples/06_subset_createv/CMakeFiles/subset_createv.dir/build
.PHONY : subset_createv/fast

#=============================================================================
# Target rules for targets named subset_full

# Build rule for target.
subset_full: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subset_full
.PHONY : subset_full

# fast build rule for target.
subset_full/fast:
	$(MAKE) -f examples/07_subset_full/CMakeFiles/subset_full.dir/build.make examples/07_subset_full/CMakeFiles/subset_full.dir/build
.PHONY : subset_full/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fenix"
	@echo "... mpi_send_recv"
	@echo "... online"
	@echo "... fenix_hello_world"
	@echo "... mpi_hello_world"
	@echo "... fenix_ring"
	@echo "... mpi_ring"
	@echo "... fenix_reduce"
	@echo "... mpi_reduce"
	@echo "... fenix_stencil_1D"
	@echo "... mpi_stencil_1D"
	@echo "... subset_create"
	@echo "... subset_createv"
	@echo "... subset_full"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

