FENIX := .
include makedefs
SRCDIR := src
OBJDIR := obj
INCLUDE := include
LIB := lib
CFLAGS := -c -std=c99 -I$(SRCDIR) -I$(INCLUDE)
all: $(LIB) $(OBJDIR) $(LIB)/libfenix.a
printVariables:
	@echo " ULFM_HOME used: $(ULFM_HOME)"
	@echo " MPICC used: $(MPICC)"
$(OBJDIR):
	@mkdir -p $(OBJDIR)
$(LIB):
	@mkdir -p $(LIB)
$(OBJDIR)/data_recovery*.o: $(SRCDIR)/data_recovery.c $(INCLUDE)/data_recovery.h 
$(OBJDIR)/fenix*.o: $(SRCDIR)/fenix.c $(INCLUDE)/fenix.h
$(OBJDIR)/hash*.o: $(SRCDIR)/hash.c $(INCLUDE)/hash.h
$(OBJDIR)/mpi_override*.o: $(SRCDIR)/mpi_override.c 
$(OBJDIR)/opt*.o: $(SRCDIR)/opt.c $(INCLUDE)/opt.h
$(OBJDIR)/process_recovery*.o: $(SRCDIR)/process_recovery.c $(INCLUDE)/process_recovery.h 
$(OBJDIR)/util*.o: $(SRCDIR)/util.c $(INCLUDE)/util.h 
OBJECTS = $(OBJDIR)/data_recovery$(1).o $(OBJDIR)/fenix$(1).o $(OBJDIR)/mpi_override$(1).o $(OBJDIR)/process_recovery$(1).o $(OBJDIR)/util$(1).o $(OBJDIR)/hash$(1).o $(OBJDIR)/opt$(1).o
$(LIB)/libfenix.a: $(call OBJECTS,)
	@echo " AR       $@"
	@ar rcs $@ $^
$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@echo " MPICC   $@"
	@${MPICC} ${CFLAGS} $< -o $@
clean: $(OBJDIR) $(LIB)
	rm -f $(OBJDIR)/* $(LIB)/* $(INCLUDE)/fenix.mod
