function(fenix_test)
  if(NOT BUILD_TESTING)
    return()
  endif()

  set(opts EXAMPLE)
  set(uniArgs SRC EXE TESTNAME RANKS FAIL_OUTPUT)
  set(polyArgs DEFINITIONS ARGS)
  cmake_parse_arguments(PARSE_ARGV 0 args "${opts}" "${uniArgs}" "${polyArgs}")

  if(NOT (DEFINED args_SRC OR (DEFINED args_EXE AND TARGET "${args_EXE}")))
    message(FATAL_ERROR "No source file or executable for fenix_test")
  endif()
  if(NOT DEFINED args_EXE)
    get_filename_component(name "${args_SRC}" NAME_WLE)
    set(args_EXE "${name}")
  endif()
  if(NOT TARGET "${args_EXE}")
    add_executable("${args_EXE}" "${args_SRC}")
    target_link_libraries("${args_EXE}" fenix MPI::MPI_CXX)
    if(DEFINED args_DEFINITIONS)
      target_compile_definitions("${args_EXE}" PRIVATE ${args_DEFINITIONS})
    endif()
  endif()
  if(NOT DEFINED args_TESTNAME)
    set(args_TESTNAME "${args_EXE}")
  endif()
  
  set(cmd_PRE "")
  set(cmd_POST "")
  if(DEFINED args_RANKS)
    set(cmd_PRE ${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG})
    set(cmd_PRE ${cmd_PRE} ${args_RANKS} ${MPIEXEC_PREFLAGS})
    set(cmd_POST ${MPIEXEC_POSTFLAGS})
  endif()
  if(DEFINED args_ARGS)
    set(cmd_POST ${cmd_POST} ${args_ARGS})
  endif()

  add_test(NAME ${args_TESTNAME}
    COMMAND ${cmd_PRE} $<TARGET_FILE:${args_EXE}> ${cmd_POST})

  if(${args_EXAMPLE})
    set_tests_properties(${args_TESTNAME} PROPERTIES LABELS "Example")
  endif()

  set(fail_regex "Signal: Aborted;terminate called after throwing;MPI_ABORT was invoked")
  if(${args_FAIL_OUTPUT})
    set(fail_regex "${fail_regex};${args_FAIL_OUTPUT}")
  endif()

  set_tests_properties(${args_TESTNAME} PROPERTIES
    FAIL_REGULAR_EXPRESSION "${fail_regex}")
endfunction()
