name: Build & Test

on:
  push:
  pull_request_target:
    types:
      - opened
      - synchronized
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Bootstrap the environment Dockerfile
        uses: docker/bake-action@v5
        with:
          files: .github/docker-compose.yml
          load: true
          target: bootstrap

      - name: Build the environment
        uses: docker/bake-action@v5
        with:
          files: .github/docker-compose.yml
          load: true
          target: env

      - name: Build Fenix
        uses: docker/bake-action@v5
        with:
          source: .
          files: .github/docker-compose.yml
          load: true
          target: fenix

      - name: Test Fenix
        run: docker run local/fenix
