name: Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'include/**'
      - 'test/**'
      - 'examples/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - '.github/workflows/ci_checks.yaml'

concurrency:
  group: ci-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: 
        include:
          - mpi_version: "openmpi@git.main=main"
            mpi_options: "+internal-hwloc +internal-libevent +internal-pmix"
            mpi_flags: "--allow-run-as-root;--map-by;:oversubscribe;--mca;async_mpi_finalize;1"
          - mpi_version: "openmpi@git.v5.0.x=main"
            mpi_options: "+internal-hwloc +internal-libevent +internal-pmix"
            mpi_flags: "--allow-run-as-root;--map-by;:oversubscribe;--mca;async_mpi_finalize;1"
          - mpi_version: "openmpi@git.v6.0.x=main"
            mpi_options: "+internal-hwloc +internal-libevent +internal-pmix"
            mpi_flags: "--allow-run-as-root;--map-by;:oversubscribe;--mca;async_mpi_finalize;1"

    name: Test against ${{ matrix.mpi_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Spack
        uses: spack/setup-spack@v3

      - name: Add Spack packages
        run: |
          spack -e ./test/CI add ${{ matrix.mpi_version }} ${{ matrix.mpi_options }}
          spack -e ./test/CI add cmake

      - name: Concretize Spack packages
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e ./test/CI concretize

      - name: Install Spack packages
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e ./test/CI install

      - name: Push packages to Fenix's build cache
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spack -e ./test/CI buildcache push --base-image ubuntu:24.04 \
            --allow-missing --update-index fenix-buildcache
        # Can safely push index even if some installs failed, only successful
        # installs will be cached
        if: ${{ !cancelled() }}

      - name: Build Fenix
        shell: spack-bash {0}
        run: |
          spack env activate --dir ./test/CI
          mkdir -p build && cd build
          cmake ../ -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx \
            -DBUILD_EXAMPLES=ON -DBUILD_TESTING=ON \
            -DMPIEXEC_PREFLAGS="${{ matrix.mpi_flags }}" \
            && make -j
        # Pushing to build cache may fail if the PR comes from a fork, but we
        # can (probably) still build and run Fenix tests.
        if: ${{ !cancelled() }}

      - name: Test Fenix
        run: |
          cd build
          ctest -V --timeout 20 --repeat until-fail:5
