name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Lint
        uses: pre-commit/actions@v3.0.1
        continue-on-error: true

      - name: Generate Suggestions
        uses: reviewdog/action-suggester@v1.21.0
        with:
          tool_name: Linter
